---
title: "Untitled"
author: "FOFANA SIKOU"
date: "12/02/2022"
output: html_document
---



```{r}
X = matrix(0,9,9)
X[1,] = sample(1:9)

for (i in 1:2){
   X[i+1,4:6]<-X[i,1:3]
   X[i+1,7:9]<-X[i,4:6]
   X[i+1,1:3]<-X[i,7:9]
}


X


```


```{r}
X = matrix(0,9,9)
X[1,] = sample(1:9)

for (i in 1:2){
   X[i+1,4:6]<-X[i,1:3]
   X[i+1,7:9]<-X[i,4:6]
   X[i+1,1:3]<-X[i,7:9]
   
   for(j in 1:8){
 
  
  X[4:6,j+1]<-X[1:3,j]
  X[4:6,j]<-X[1:3,j]
  X[7:9,j+1]<-X[4:6,j]
  X[7:9,j]<-X[4:6,j]
  }
}

X
```


Grille = [[1, 9, 7, 4, 3, 2, 5, 6, 8],
          [5, 6, 8, 1, 9, 7, 4, 3, 2],  
          [4, 3, 2, 5, 6, 8, 1, 9, 7], 
          [7, 1, 9, 2, 4, 3, 8, 5, 6], 
          [8, 5, 6, 7, 1, 9, 2, 4, 3], 
          [2, 4, 3, 8, 5, 6, 7, 1, 9], 
          [6, 7, 1, 9, 2, 4, 3, 8, 5],
          [3, 8, 5, 6, 7, 1, 9, 2, 4], 
          [9, 2, 4, 3, 8, 5, 6, 7, 1]]

print(Grille)         


```{r}
X = matrix(0,9,9)
X[1,] = sample(1:9)

a=X[2,4:6] <- X[1,1:3]

b=X[2,7:9]<-X[1,4:6]

c=X[2,1:3]<-X[1,7:9]

d=X[3,4:6]<- X[2,1:3]

e=X[3,7:9]<-X[2,4:6]

f=X[3,1:3]<-X[2,7:9]

g=X[3,7:9]<-X[2,4:6]

k=X[4:6,2]<-X[1:3,1]

l=X[4:6,3]<-X[1:3,2]

m=X[4:6,1]<-X[1:3,3]

n=X[4:6,5]<-X[1:3,4]

p=X[4:6,6]<-X[1:3,5]

r=X[4:6,4]<-X[1:3,6]

t=X[4:6,8]<-X[1:3,7]

s=X[4:6,9]<-X[1:3,8]

w=X[4:6,7]<-X[1:3,9]

z1=X[7:9,2]<-X[4:6,1]

z2=X[7:9,3]<-X[4:6,2]

z3=X[7:9,1]<-X[4:6,3]

z4=X[7:9,5]<-X[4:6,4]

z5=X[7:9,6]<-X[4:6,5]

z6=X[7:9,4]<-X[4:6,6]

z7=X[7:9,8]<-X[4:6,7]

z8=X[7:9,9]<-X[4:6,8]

z9=X[7:9,7]<-X[4:6,9]


X
```






```{r}
X = matrix(0,9,9)
X[1,] = sample(1:9)

X

for (i in 1:9){
   X[i+1,4:6]<-X[i,1:3]
  X[i+1,7:9]<-X[i,4:6]
  X[i+1,1:3]<-X[i,7:9]
  for(j in 1:9){
 
  
  X[4:6,j+1]<-X[1:3,j]
  X[4:6,j]<-X[1:3,j]
  X[7:9,j+1]<-X[4:6,j]
   X[7:9,j]<-X[4:6,j]
  }
}

X

X[i+1][j+3]<-X[i][j]

X[1,]

for (i in 1:9 ){
  
   for (j in 1:9)
   {
  X[i+1,j+3:6]<-X[i,j:3]

   }
}
X
a=X[2,4:6] <- X[1,1:3]

b=X[2,7:9]<-X[1,4:6]

c=X[2,1:3]<-X[1,7:9]

d=X[3,4:6]<- X[2,1:3]

e=X[3,7:9]<-X[2,4:6]

f=X[3,1:3]<-X[2,7:9]

i=X[3,7:9]<-X[2,4:6]

k=X[4:6,2]<-X[1:3,1]

l=X[4:6,3]<-X[1:3,2]

m=X[4:6,1]<-X[1:3,3]

n=X[4:6,5]<-X[1:3,4]

p=X[4:6,6]<-X[1:3,5]

r=X[4:6,4]<-X[1:3,6]

t=X[4:6,8]<-X[1:3,7]

s=X[4:6,9]<-X[1:3,8]

w=X[4:6,7]<-X[1:3,9]

z1=X[7:9,2]<-X[4:6,1]

z2=X[7:9,3]<-X[4:6,2]

z3=X[7:9,1]<-X[4:6,3]

z4=X[7:9,5]<-X[4:6,4]

z5=X[7:9,6]<-X[4:6,5]

z6=X[7:9,4]<-X[4:6,6]

z7=X[7:9,8]<-X[4:6,7]

z8=X[7:9,9]<-X[4:6,8]

z9=X[7:9,7]<-X[4:6,9]




X

```


